### PR TITLE
Created ArmFPIDController

### PR DESCRIPTION
**Pull request by lacedwithennui**

### CODE REVIEW

**Comment by mxgordon** [comment]
tbh I don't think this is necessary, all this should just be implemented in the `ArmBase`

**Comment by lacedwithennui** [comment]
but it's schmexy tho

**Comment by lacedwithennui** [comment]
what if I make it non-exclusive to arms, for use on like elevators and other mechanisms so it can be re-used more

feedforward is like, more than just setpoint and stuff and running it on the Rio would be easier in its own class

**Comment by lacedwithennui** [comment]
also there's always the "it's nice to have" argument

**Comment by mxgordon** [comment]
I agree that it would be nice to have, however, I don't think it should be its own controller. Instead, just make an `FPIDSubsystemBase` (which subclasses PIDSubystemBase`) that can apply all these constants. Then you can make `ArmBase` and `ElevatorBase` that subclass it, with only a few lines of code.

**Pull request closed without merging**
